### ISSUE TITLE
Broken Search

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [Isaiah-Hamilton/live-atc#13]
Search leads to 404 page

**Comment by bhavik001** [comment]
Hey @Isaiah-Hamilton 
Can I work on this issue?

**Comment by Isaiah-Hamilton** [comment]
@bhavik001 This issue has been fixed with c80449c5e5deb3d454d1af2fe7a3e2ba49e6d0fc, but there are still more [issues](https://github.com/Isaiah-Hamilton/live-atc/issues) for you to work on if you still want.
