### ISSUE TITLE
Add Prettier

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [Isaiah-Hamilton/live-atc#9]
Add Prettier to format code.

**Comment by bhavik001** [comment]
Hello @Isaiah-Hamilton !
Can you assign me this issue I am interested in working on this issue.

**Comment by Isaiah-Hamilton** [comment]
@bhavik001 I'm more than happy for you to work on this issue!

**Comment by bhavik001** [comment]
Hey @Isaiah-Hamilton 
I have created pull request please review it and let me know if I have to make any changes.
